### ISSUE TITLE
Roles: Audit all existing titles and membership

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#519]
Motivation: Over the years, the Project has evolved more quickly than `roles.json` (that renders to https://www.astropy.org/team) can be updated. As a result, there are now roles that do not exist anymore (or inactive) and people who do not really fill existing roles anymore. I would like to submit a series of PRs to update this listing, or at least put the roles in discussion.

Depends on:

* Developer survey results (2023 and maybe also 2022) -- who replied and who MIA?
* Community discussions (on this issue, on related PRs, mailing lists, Slack, etc)

Also might be relevant:

* #167

Existing roles (as of 2023-03-06):

- [x] Coordination committee member -- This is decided by election. No further action needed.
- [x] Ombudsperson -- Still true. No further action needed.
- [ ] Community engagement coordinator -- Do we really need so many sub-roles? Can this be all merged into one when we hire a proper community manager?
- [ ] Astropy GSoC coordinator -- #518 
- [ ] Learn Team -- Do we really need so many sub-roles? Are these even still active? Can this be simplified?
- [x] Finance committee member -- This committee is active. No further action needed.
- [ ] Documentation infrastructure maintainer -- Can this be merged with "Testing infrastructure maintainer"? I am active in both and they do overlap a lot.
- [ ] Affiliated package review editor -- They are active. No further action needed.
- [ ] Astropy.org web page maintainer -- I don't know what this means. If this is simply who holds the DNS account, I think this is overkill and can be removed. If not, please clarify what this role actually does.
- [ ] Astropy-helpers maintainer -- #517 
- [ ] DevOps and Operations Specialist -- We tried to hire an official person to do this but that person is no longer active and the position has lapsed. I say we remove this because this is now split into other roles already mentioned (e.g., infrastrucure, core).
- [ ] Testing infrastructure maintainer -- Can this be merged with "Documentation infrastructure maintainer"? I am active in both and they do overlap a lot.
- [ ] Package template maintainer -- We plan to retire the template in favor of OpenAstronomy's, so we should remove this role because it is no longer actively maintained. See https://github.com/astropy/package-template/issues/519
- [ ] CI-helpers maintainer -- #517 
- [ ] Distribution coordinator -- It is very hard to vet this one since distro activities happen outside the purview of Astropy. I know some of these people are active while hardly heard from the other ones, though that does not mean they are not doing anything either. Also, other distros out there might be distributing `astropy` also but we don't list them. Ideas welcome.
- [ ] Dev-telecon coordinator -- Moritz has been hosting the last few by himself. Is this role really working out or do we need something else? Is it overkill to have a named role just for this telecon?
- [ ] Release team -- I only am aware of Tom R and Simon C who are actively doing core releases. I vote to remove the inactive ones.
- [ ] Core astropy package maintainer (general) -- This one is relative new. Both Derek and I are active. I guess no further action needed?
- [x] Subpackage: `constants` -- This is low-activity and looks about right. No further action needed.
- [ ] Subpackage: `convolution` -- Is Axel still active? Need to find out.
- [ ] Subpackage: `coordinates` -- So many maintainers, truly? Need to double check.
- [x] Subpackage: `cosmology` -- Single point of failure though maintainer is active. Looks about right. 😆 No further action needed.
- [x] Subpackage: `io.ascii` -- Looks about right. No further action needed.
- [x] Subpackage: `io.fits` -- Single point of failure though maintainer is active. Looks about right. 😆 No further action needed.
- [ ] Subpackage: `io.misc` -- Should we replace Ed with William?
- [ ] Subpackage: `io.votable` -- Have not seen Boch in a while. Need to find out.
- [x] Subpackage: `modeling` -- Looks about right. No further action needed.
- [x] Subpackage: `nddata` -- Matt is still stuck with it but has a plan that is out of scope here. No further action needed.
- [x] Subpackage: `samp` -- Yup, no one. Someday maybe https://github.com/astropy/pyvo/issues/155
- [x] Subpackage: `stats` -- Single point of failure though maintainer is active. Looks about right. 😆 No further action needed.
- [x] Subpackage: `table` -- Looks about right. No further action needed.
- [x] Subpackage: `time` -- Looks about right. No further action needed.
- [ ] Subpackage: `timeseries` -- Have not seen a lot of activities here. Need to double check.
- [ ] Subpackage: `uncertainties` -- Have not seen a lot of activities here. Need to double check.
- [x] Subpackage: `units` -- Looks about right. No further action needed.
- [ ] Subpackage: `utils` -- I think this is mostly Marten and I nowadays. Need to double check.
- [x] Subpackage: `visualization` -- Looks about right. No further action needed.
- [x] Subpackage: `wcs` -- Looks about right. No further action needed.
- [ ] Coordinated: `astroquery` -- Is Clara still active? Need to double check.
- [x] Coordinated: `astropy-healpix` -- This is low-activity and looks about right. No further action needed.
- [ ] Coordinated: `photutils` -- Need to double check.
- [ ] Coordinated: `ccdproc` -- Is Matt still developing it? Need to double check.
- [ ] Coordinated: `specutils` -- Some names are no longer active there. Need to double check.
- [ ] Coordinated: `reproject` -- Is Stuart still involved? Need to double check.
- [x] Coordinated: `regions` -- Looks about right. No further action needed.
- [x] Coordinated: `asdf-astropy` -- Looks about right. No further action needed.
- [ ] Coordinated: `specreduce` -- This entry is completely missing. We need to add this.

**Comment by mhvk** [comment]
For distributions, that is only useful it if includes *which* distributions the person(s) is/are responsible for.

**Comment by mhvk** [comment]
For `coordinates`, I think @eteq has been rather inactive (likely despite himself), as has @adrn. @StuartLittlefair and @eerovaher are active.

`uncertainties` is indeed a bit inactive, though I've had a few PRs recently. @eteq has not been involved in it recently (wish he were, as perhaps does he!). One of quite a few where a co-maintainer would help... (@byrdie and @nstarman are generally interested in it)

For `utils`, similarly more people would be useful. For `utils.masked`, @nstarman has been contributing. For `utils.iers`, @taldcroft has contributed quite a bit.

**Comment by mhvk** [comment]
More high-level, thanks for doing this! I hope the developer survey helps clarify some bits; agreed that we should remove people from the list if they are inactive -- without prejudice of course!

**Comment by byrdie** [comment]
I'd be certainly be interested in co-maintaining `uncertainties`, but I can't say that I've contributed to that subpackage yet.

**Comment by pllim** [comment]
Thanks! I don't expect everything will be resolved in a blink. I will certainly consider all the comments here when I bring this to CoCo and wherever we have to discuss.

**Comment by mhvk** [comment]
@byrdie - understood - my comment was a bit more an expression of hope for the future!

**Comment by byrdie** [comment]
@mhvk, agreed! I'm just eager to help in any way I can.

**Comment by hamogu** [comment]
In my opinion, we needs to distinguish between credit for work and a "contract list" like a phone book. To me, the team page is meant to the latter and thus there are a number of roles on there that are pretty small in terms of hours/year. For example see https://github.com/astropy/astropy.github.com/pull/507, where we tweaked "Astropy.org web page maintainer", to make it clear whom to contact for DNS upkeep and configuration. That's way, way less work than e.g. maintaining infrastructure, but if I have a problem with the DNS configuration, I need to know whom to talk to.

Another example is having sub-roles for distributions. Originally, every distribution had a sub-role, like "Debian maintainer", "arch linux maintainer", "macports maintainer" etc. Then, we decided that that gives way too much weight to tasks that are almost automatic (@olebole contributes a lot back to astropy form Debian's tests on exotic architectures, but most maintainers just update the version number every now and then) and we removed the sub-roles. The result is that the entry is now almost pointless, because we don't even know why some of those names are on there.

So, the question for what's listed as a role or sub-role should not be "how much work is it?" but "Is this a distinct task where someone might need contact information for the person doing that task?" For that, I would support linking contact information (e.g. email or slack channel or GH handle, depending on the role). The infrastructure team is well organized, talks to each other and coordinates among themselves who does what, so one contact is sufficient. On the other hand, the twitter person won't be able to help with a discourse configuration issue or the other way around, so they are listed as separate sub-roles.

In contrast, the credit for work is on https://www.astropy.org/credits.html. 

I'm all for cleaning this up in a systematic effort, but we have to take care not to throw out the baby with the bathwater.

**Comment by pllim** [comment]
> distinguish between credit for work and a "contract list" like a phone book

I don't know what people really use this page for but it is apparently high visibility. Personally, I only look at the subpackage section so I know who to bug to review PRs. But I have also heard others use this page "as CVs" (unconfirmed). So, we cannot tell people how to use this page, but rather we should try to reflect the state of task assignments without appear to overly emphasizing a subset of them.

https://www.astropy.org/credits.html is a totally different beast. You can spend a lot of time maintaining something and not end up on that page until years later. If that is the sole "metric" we use for "credit for work," I would worry.

> whom to contact for DNS upkeep

This is almost a security risk. I don't think we should even mention it publicly any server-side or account specific info (that includes Twitter).

> The infrastructure team is well organized

Just because one part is well organized now does not mean it will be in a month. That is the inherent risk of OSS where people come and go. We should not give more "air time" (for lack of better words, it is late here) to things because they are not well organized. Therefore, I disagree with this being a reason on whether something end up on the page or not.

This reply also applies to https://github.com/astropy/astropy.github.com/pull/524#issuecomment-1457332824 .

> take care not to throw out the baby with the bathwater

I agree, though I think a lot of debates will occur on which one is the baby and which one the bathwater. 😹

**Comment by hamogu** [comment]
>> whom to contact for DNS upkeep
> This is almost a security risk. I don't think we should even mention it publicly any server-side or account specific info (that includes Twitter).

But then, how do project members know whom to ask? Needs to written down somewhere?

**Comment by hamogu** [comment]
> The infrastructure team is well organized

> Just because one part is well organized now does not mean it will be in a month. 

Sure. But when that happens, and the tasks get split over more people we can add more roles again. This is a living document, pretty easy to change again.

**Comment by mhvk** [comment]
Like @hamogu and you, I mostly use the page to find out who to ping (and mostly for the core subpackages). All the suggested changes seem to be just to clarify that, which I think is a good idea. Let's not worry about how else the page may used outside of astropy.

**Comment by eteq** [comment]
@pllim 

>  Astropy.org web page maintainer 

This is the maintainer in the sense of a sub-package, someone who maintains the repo and so on.  This also includes DNS, etc. The `sites.json` is nominally part of that, but it's a lot harder to keep up with than some of the other stuff.  Maybe we should add a separate `sites.json` role to highlight that's extra additional work? (And e.g., I would *not* put myself there since I haven't had enough time to keep up with it)

**Comment by SarveshVGharat** [comment]
I didn't see anything related to AstroPy in GSOC 2023 list of projects. 
Can anyone confirm if there are some openings through GSOC or not?

**Comment by pllim** [comment]
I got feedback from several different people. Seems like there are very different opinions on what this page represents and what should or should not be on it. I think I need to step back a little and look at the bigger picture first. 💭
